import React, { useCallback, useEffect, useState } from "react";
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  ActivityIndicator,
  Alert,
} from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useFocusEffect } from "expo-router";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import { Ionicons } from "@expo/vector-icons";
import { api } from "../../src/lib/api";
import { useAuth } from "../../src/contexts/AuthContext";
import { colors, fonts, radii, space } from "../../src/theme";

export default function InvoiceScreen() {
  const { user } = useAuth();
  const [client, setClient] = useState("");
  const [desc, setDesc] = useState("");
  const [amount, setAmount] = useState("");
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [creating, setCreating] = useState(false);
  const [invoices, setInvoices] = useState<any[]>([]);

  const load = useCallback(async () => {
    try {
      const res = await api.listInvoices();
      setInvoices(res.invoices || []);
    } catch {}
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  useFocusEffect(
    useCallback(() => {
      load();
    }, [load])
  );

  const buildHtml = (inv: any, freelancerName: string) => `
    <html>
    <head><meta charset="utf-8" />
    <style>
      body { font-family: -apple-system, sans-serif; padding: 40px; color: #111; }
      .row { display: flex; justify-content: space-between; align-items: flex-start; }
      .brand { color: #FF5C00; font-weight: 700; font-size: 20px; letter-spacing: 4px; }
      h1 { font-size: 36px; margin: 24px 0 4px; }
      .muted { color: #666; font-size: 12px; }
      .box { border: 1px solid #ddd; border-radius: 8px; padding: 20px; margin-top: 24px; }
      .total { font-size: 32px; font-weight: 700; color: #111; }
      .row2 { display: flex; justify-content: space-between; margin-top: 8px; }
    </style></head>
    <body>
      <div class="row">
        <div class="brand">LEADFORGE</div>
        <div class="muted">${inv.invoice_number}</div>
      </div>
      <h1>Invoice</h1>
      <div class="muted">Date: ${inv.date}</div>
      <div class="box">
        <div class="muted">FROM</div>
        <div style="font-size:18px;font-weight:600;margin-top:4px">${freelancerName || "Freelancer"}</div>
      </div>
      <div class="box">
        <div class="muted">BILL TO</div>
        <div style="font-size:18px;font-weight:600;margin-top:4px">${inv.client_name}</div>
      </div>
      <div class="box">
        <div class="muted">DESCRIPTION</div>
        <div style="font-size:14px;margin-top:8px;line-height:1.6">${inv.description}</div>
        <div class="row2"><div class="muted">AMOUNT DUE</div><div class="total">$${Number(inv.amount).toFixed(2)}</div></div>
      </div>
      <div style="margin-top:40px;color:#999;font-size:11px;text-align:center">Generated by LeadForge AI</div>
    </body></html>`;

  const handleCreate = async () => {
    if (!client.trim() || !desc.trim() || !amount.trim()) {
      Alert.alert("Missing fields", "Fill all required fields.");
      return;
    }
    const amt = parseFloat(amount);
    if (isNaN(amt) || amt <= 0) {
      Alert.alert("Invalid amount", "Enter a valid number.");
      return;
    }
    setCreating(true);
    try {
      const inv = await api.createInvoice({
        client_name: client,
        description: desc,
        amount: amt,
        date,
      });
      // Clear form & refresh list immediately on backend success
      setClient("");
      setDesc("");
      setAmount("");
      await load();
      // PDF generation/share is best-effort (may not work on web preview)
      try {
        const html = buildHtml(inv, user?.name || "");
        const { uri } = await Print.printToFileAsync({ html });
        const canShare = await Sharing.isAvailableAsync();
        if (canShare) {
          await Sharing.shareAsync(uri, { mimeType: "application/pdf", dialogTitle: "Share Invoice" });
        } else {
          Alert.alert("Saved", "Invoice created. PDF sharing unavailable on this platform.");
        }
      } catch (pdfErr: any) {
        Alert.alert("Created", `Invoice ${inv.invoice_number} saved. PDF preview unavailable on this platform.`);
      }
    } catch (e: any) {
      Alert.alert("Error", e.message || "Failed");
    } finally {
      setCreating(false);
    }
  };

  const handleSharePast = async (inv: any) => {
    try {
      const html = buildHtml(inv, user?.name || "");
      const { uri } = await Print.printToFileAsync({ html });
      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, { mimeType: "application/pdf" });
      }
    } catch (e: any) {
      Alert.alert("Error", e.message || "Failed");
    }
  };

  return (
    <SafeAreaView style={styles.safe} edges={["top"]}>
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : undefined}
        style={{ flex: 1 }}
      >
        <ScrollView
          contentContainerStyle={{ padding: space.lg, paddingBottom: 120 }}
          keyboardShouldPersistTaps="handled"
        >
          <Text style={styles.overline}>INVOICE</Text>
          <Text style={styles.title}>Get paid</Text>
          <Text style={styles.subtitle}>Generate a PDF invoice in seconds.</Text>

          <View style={{ height: space.lg }} />
          <Text style={styles.label}>CLIENT NAME</Text>
          <TextInput
            testID="invoice-client-input"
            value={client}
            onChangeText={setClient}
            placeholder="Acme Corp"
            placeholderTextColor={colors.textTertiary}
            style={styles.input}
          />

          <View style={{ height: space.md }} />
          <Text style={styles.label}>SERVICE DESCRIPTION</Text>
          <TextInput
            testID="invoice-desc-input"
            value={desc}
            onChangeText={setDesc}
            placeholder="Logo design package, 3 concepts + revisions"
            placeholderTextColor={colors.textTertiary}
            multiline
            numberOfLines={3}
            style={[styles.input, { minHeight: 80, textAlignVertical: "top" }]}
          />

          <View style={{ height: space.md }} />
          <View style={{ flexDirection: "row", gap: space.md }}>
            <View style={{ flex: 1 }}>
              <Text style={styles.label}>AMOUNT (USD)</Text>
              <TextInput
                testID="invoice-amount-input"
                value={amount}
                onChangeText={setAmount}
                placeholder="500"
                placeholderTextColor={colors.textTertiary}
                keyboardType="decimal-pad"
                style={styles.input}
              />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.label}>DATE</Text>
              <TextInput
                testID="invoice-date-input"
                value={date}
                onChangeText={setDate}
                placeholder="YYYY-MM-DD"
                placeholderTextColor={colors.textTertiary}
                style={styles.input}
              />
            </View>
          </View>

          <View style={{ height: space.lg }} />
          <TouchableOpacity
            testID="invoice-generate-btn"
            style={[styles.btn, creating && { opacity: 0.7 }]}
            onPress={handleCreate}
            disabled={creating}
            activeOpacity={0.8}
          >
            {creating ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <>
                <Ionicons name="document-text-outline" size={16} color="#fff" />
                <Text style={styles.btnText}>GENERATE & SHARE PDF</Text>
              </>
            )}
          </TouchableOpacity>

          <View style={{ height: space.xl }} />
          <Text style={styles.label}>PAST INVOICES</Text>
          {invoices.length === 0 ? (
            <Text style={styles.subtitle}>No invoices yet.</Text>
          ) : (
            invoices.map((inv) => (
              <TouchableOpacity
                key={inv.id}
                testID={`invoice-${inv.id}`}
                onPress={() => handleSharePast(inv)}
                style={styles.invCard}
                activeOpacity={0.7}
              >
                <View style={{ flex: 1 }}>
                  <Text style={styles.invClient}>{inv.client_name}</Text>
                  <Text style={styles.invMeta}>
                    {inv.invoice_number} · {inv.date}
                  </Text>
                </View>
                <Text style={styles.invAmt}>${Number(inv.amount).toFixed(2)}</Text>
                <Ionicons name="share-outline" size={18} color={colors.textTertiary} style={{ marginLeft: space.sm }} />
              </TouchableOpacity>
            ))
          )}
        </ScrollView>
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  overline: { fontFamily: fonts.bodyMedium, fontSize: 11, color: colors.primary, letterSpacing: 2 },
  title: { fontFamily: fonts.heading, fontSize: 28, color: colors.textPrimary, marginTop: 4 },
  subtitle: { fontFamily: fonts.body, fontSize: 13, color: colors.textSecondary, marginTop: 4 },
  label: { fontFamily: fonts.bodyMedium, fontSize: 11, color: colors.textTertiary, letterSpacing: 1.5, marginBottom: space.xs },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    paddingHorizontal: space.md,
    paddingVertical: 12,
    color: colors.textPrimary,
    fontFamily: fonts.body,
    fontSize: 14,
  },
  btn: {
    backgroundColor: colors.primary,
    borderRadius: radii.md,
    paddingVertical: 14,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    gap: space.sm,
  },
  btnText: { color: "#fff", fontFamily: fonts.bodySemi, fontSize: 13, letterSpacing: 1.5 },
  invCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: space.md,
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.md,
    marginTop: space.sm,
  },
  invClient: { fontFamily: fonts.headingMedium, fontSize: 15, color: colors.textPrimary },
  invMeta: { fontFamily: fonts.mono, fontSize: 11, color: colors.textTertiary, marginTop: 2 },
  invAmt: { fontFamily: fonts.monoBold, fontSize: 16, color: colors.success },
});
